// <auto-generated />
using System;
using AdaPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaPlatform.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925064817_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdaPlatform.Domain.Fleet.CountingDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "DeviceNumber")
                        .IsUnique();

                    b.ToTable("CountingDevices");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Fleet.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Depot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("StandingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Traction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Block", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Line", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Pattern", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("FirstStopName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastStopName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("LengthKm")
                        .HasColumnType("float");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("TargetCode")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("LineId");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.PatternStop", b =>
                {
                    b.Property<int>("PatternCode")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("StopCode")
                        .HasColumnType("int");

                    b.HasKey("PatternCode", "Sequence");

                    b.HasIndex("StopCode");

                    b.ToTable("PatternStops");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Stop", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<double?>("Altitude")
                        .HasColumnType("float");

                    b.Property<double?>("JtskX")
                        .HasColumnType("float");

                    b.Property<double?>("JtskY")
                        .HasColumnType("float");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tariffs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.DoorCount", b =>
                {
                    b.Property<long>("StopVisitId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountingDeviceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Alightings")
                        .HasColumnType("int");

                    b.Property<int>("Boardings")
                        .HasColumnType("int");

                    b.Property<bool>("IsFlaggedInvalid")
                        .HasColumnType("bit");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StopVisitId", "CountingDeviceId");

                    b.HasIndex("CountingDeviceId");

                    b.ToTable("DoorCounts");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.StopVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Alightings")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Boardings")
                        .HasColumnType("int");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPassThrough")
                        .HasColumnType("bit");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("StopCode")
                        .HasColumnType("int");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StopCode");

                    b.HasIndex("TripId", "Sequence")
                        .IsUnique();

                    b.ToTable("StopVisits");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Alightings")
                        .HasColumnType("int");

                    b.Property<string>("BlockCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Boardings")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialDelaySeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PatternCode")
                        .HasColumnType("int");

                    b.Property<int?>("SecondVehicleId")
                        .HasColumnType("int");

                    b.Property<long?>("SourceFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockCode");

                    b.HasIndex("SecondVehicleId");

                    b.HasIndex("SourceFileId");

                    b.HasIndex("StartTime");

                    b.HasIndex("PatternCode", "StartTime");

                    b.HasIndex("VehicleId", "StartTime");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Quality.DeviceFault", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DeviceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("VehicleId", "DeviceNumber", "From");

                    b.ToTable("DeviceFaults");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Raw.DeviceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Alightings")
                        .HasColumnType("int");

                    b.Property<bool?>("Alive")
                        .HasColumnType("bit");

                    b.Property<string>("BlockCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Boardings")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int?>("DelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("DeviceNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvalidDevices")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LastStopCode")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("OnBoard")
                        .HasColumnType("int");

                    b.Property<int?>("OnBoardChange")
                        .HasColumnType("int");

                    b.Property<int?>("PatternCode")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SourceFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusRegister")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StopCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("SourceFileId", "LineNumber")
                        .IsUnique();

                    b.HasIndex("VehicleId", "Time");

                    b.HasIndex("VehicleId", "DeviceNumber", "Time");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Raw.SourceFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineCount")
                        .HasColumnType("int");

                    b.Property<int>("MalformedLineCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("VehicleId", "ServiceDate");

                    b.ToTable("SourceFiles");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Fleet.CountingDevice", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Fleet.Vehicle", "Vehicle")
                        .WithMany("CountingDevices")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Pattern", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Network.Line", "Line")
                        .WithMany("Patterns")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.PatternStop", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Network.Pattern", "Pattern")
                        .WithMany("Stops")
                        .HasForeignKey("PatternCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdaPlatform.Domain.Network.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.DoorCount", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Fleet.CountingDevice", "CountingDevice")
                        .WithMany()
                        .HasForeignKey("CountingDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdaPlatform.Domain.Operations.StopVisit", "StopVisit")
                        .WithMany("DoorCounts")
                        .HasForeignKey("StopVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountingDevice");

                    b.Navigation("StopVisit");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.StopVisit", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Network.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdaPlatform.Domain.Operations.Trip", "Trip")
                        .WithMany("StopVisits")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.Trip", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Network.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdaPlatform.Domain.Network.Pattern", "Pattern")
                        .WithMany()
                        .HasForeignKey("PatternCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdaPlatform.Domain.Fleet.Vehicle", "SecondVehicle")
                        .WithMany()
                        .HasForeignKey("SecondVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdaPlatform.Domain.Raw.SourceFile", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdaPlatform.Domain.Fleet.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Pattern");

                    b.Navigation("SecondVehicle");

                    b.Navigation("SourceFile");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Quality.DeviceFault", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Operations.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Raw.DeviceEvent", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Raw.SourceFile", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Raw.SourceFile", b =>
                {
                    b.HasOne("AdaPlatform.Domain.Fleet.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdaPlatform.Domain.Fleet.Vehicle", b =>
                {
                    b.Navigation("CountingDevices");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Line", b =>
                {
                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Network.Pattern", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.StopVisit", b =>
                {
                    b.Navigation("DoorCounts");
                });

            modelBuilder.Entity("AdaPlatform.Domain.Operations.Trip", b =>
                {
                    b.Navigation("StopVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
